# Predicting kidney cancer progression

Estimated time for reading: **20** minutes


<details><summary>The main info</summary>
<h3>Context</h3> 

<p>Kidney cancer remains a significant challenge in modern medicine despite notable progress in diagnostic and treatment methods. The issue of predicting the risk of disease progression is particularly relevant, as even after radical treatment, some patients experience recurrences or metastases. These circumstances complicate the selection of optimal treatment strategies and significantly impact patients' quality of life and survival rates.</p>

<h3>Research Object</h3>

<p>The process of predicting the risk of kidney cancer progression based on clinical individual characteristics of patients and data from patients treated at the Lviv Oncology Center between 2007 and 2018.</p>

<h3>Research Subject</h3>

<p>The use of machine learning methods to build a model that predicts the risk of disease progression, taking into account individual patient characteristics (age, gender, tumor process stage, histological and immunohistochemical study results).</p>

<h3>Research Goal</h3>

<p>The goal of the research is to develop a model that predicts the risk of kidney cancer progression using machine learning methods to improve treatment strategies and enhance therapy efficiency.</p>

<h3>Relevance</h3> 
<p>The relevance of the study lies in the fact that, despite modern medical advancements and the availability of various treatment methods, kidney cancer (KC) remains a significant problem. Most cases are diagnosed at a localized stage, where the tumor has not yet spread beyond the kidney. However, even after radical treatment, disease progression occurs in a significant proportion of patients during follow-up, manifesting as local recurrences, distant metastases, or multifocal kidney cancer.</p> <p>Particular attention is required for patients with locally advanced KC, including cases with tumor extension to perirenal fat, the adrenal gland, or the presence of tumor thrombus in the renal or inferior vena cava. The presence of isolated metastases in regional lymph nodes also significantly increases the risk of adverse outcomes and complicates treatment strategy selection, as these patients face higher risks of complications and disease progression.</p> <p>Additionally, patients with distant metastases at initial diagnosis often present challenges in disease management. Progression is typically observed during systemic therapy evaluation (targeted therapy, immunotherapy), complicating the choice of further treatment strategies. Literature data indicate that 30-40% of radically treated patients experience progression, with the risk of recurrence or metastasis reaching up to 50% in some cases, emphasizing the necessity of risk prediction based on individual patient characteristics.</p> <p>Thus, developing a model that predicts the risk of disease progression based on individual patient characteristics—such as age, gender, tumor stage, and results of pathological and immunohistochemical studies—is an essential task. This approach will help clinicians make more informed decisions regarding treatment strategies and disease control, provide patients with accurate prognostic information, and enhance therapy efficiency while reducing mortality rates from this condition.</p>

<h2>Table of Contents</h2>

<div class="alert alert-block alert-info" style="margin-top: 20px">
<ol>
    <li><a href="#data_acquisition">Data Acquisition</a>
    <li><a href="#basic_insight">Basic Insight of Dataset</a></li>
</ol>

</div>
<hr>

<h3>Data Acquisition</h3> 

<p> In this research, the dataset contains depersonalized clinical data of patients with kidney cancer who were treated at the Lviv Oncology Center from 2007 to 2018. The dataset was initially stored in an Excel file format (.xlsx) and later converted to a CSV file format with UTF-8 encoding and semicolon (;) as a delimiter to ensure compatibility with Python-based data analysis tools.<br> </p> 

<p> The dataset includes patient characteristics such as age, gender, tumor stage, histological, and immunohistochemical findings. The data has been carefully depersonalized to ensure compliance with ethical and legal standards regarding patient confidentiality. </p> 

<p> To work with the dataset, the <b>Pandas Library</b> in Python is used, as it provides a robust framework for reading and manipulating CSV files. The dataset is loaded into a Pandas DataFrame, where data preprocessing, cleaning, and further analysis are performed. The semicolon delimiter is explicitly specified during data loading to correctly parse the data structure. </p> 

<p> This step is critical for preparing the data for machine learning modeling and ensuring its usability in predictive analysis of kidney cancer progression. </p>

In [1]:
#install specific version of libraries used in  lab
#! mamba install pandas==1.3.3  -y
#! mamba install numpy=1.21.2 -y
#! pip install pandas

In [1]:
# import libraries
import pandas as pd
import numpy as np

<h2>Read Data</h2>
<p>
We use <code>pandas.read_csv()</code> function to read the csv file. In the brackets, we put the file path along with a quotation mark so that pandas will read the file into a dataframe. The file path is a local file address.<br>

</p>

In [2]:
file_path = 'data_table2.csv'

In [3]:
# Read the  file by the path provided above, and assign it to variable "df"
df = pd.read_csv(file_path, delimiter=';', encoding='utf-8', on_bad_lines='skip')

After reading the dataset, we can use the <code>dataframe.head(n)</code> method to check the top n rows of the dataframe, where n is an integer. Contrary to <code>dataframe.head(n)</code>, <code>dataframe.tail(n)</code> will show you the bottom n rows of the dataframe.

In [4]:
df.head(5).style.set_properties(**{'text-align': 'left'}).set_table_styles([
    {'selector': 'th', 'props': [('text-align', 'left')]}])

In [5]:
df.columns

Index(['вік', 'R', 'sex', 'D/S', 'Lok', 'рТ', 'pТ1a', 'pT1b',
       'інвазія в паранефральну клітковину', 'V+', 'v.renalis', 'v.cava inf.',
       'pT3a', 'pT3b', 'pT3c', 'інвазія в наднирник', 'MRT N', 'KT N', 'УздN',
       'pN', 'pN+', 'M', 'Pulmon', 'glandula suprarenalis', 'Os', 'Hepar\n',
       'No regional lymph node metаstasis\n', 'інше', 'G', 'Stage', 'операція',
       'adrenalectomy', 'світлоклітинний НКР', 'папілярний НКР',
       'хромофобний НКР', 'Bellini', 'лейоміосаркома',
       'вогнища некрозу пухлини', 'саркоматоїдні елементи',
       'мікросудинна інвазія', 'супутн', 'рецидив', 'P.m.mts',
       'метахронний білатеральний НКР', 'ост. візит', 'дата смерті',
       'причина смерті', 'Adjuv.XT', 'Паліат.ХТ', 'Паліат.ПТ'],
      dtype='object')

In [6]:
df.shape[0]

1000

In [7]:
df.shape[1]

50

In [8]:
new_column_names = ['Age', 'R', 'Sex', 'D/S', 'Location', 'pT', 'pT1a', 'pT1b', 'Invasion', 'V+',
 'Renal Vein Invasion', 'Inferior Vena Cava Invasion', 'pT3a', 'pT3b', 'pT3c', 'Adrenal Gland Invasion',
 'MRT N', 'CT N', 'Ultrasound N', 'pN', 'pN+', 'M', 'Lung Metastases', 'Adrenal Gland', 'Bone Metastases',
 'Liver Metastases', 'No Regional Lymph Node Metastasis', 'Other', 'G', 'Stage', 'Surgery', 'Adrenalectomy',
 'Clear Cell RCC', 'Papillary RCC', 'Chromophobe RCC', 'Bellini', 'Leiomyosarcoma', 'Tumor Necrosis Foci',
 'Sarcomatoid Elements', 'Microvascular Invasion', 'Comorbidities', 'Recurrence', 'Primary Multiple Metastases',
 'Metachronous Bilateral RCC', 'Last Visit', 'Date of Death', 'Cause of Death',
 'Adjuvant Chemotherapy', 'Palliative Chemotherapy', 'Palliative Therapy']

In [9]:
df.columns = new_column_names
df

,Age,R,Sex,D/S,Location,pT,pT1a,pT1b,Invasion,V+,...,Comorbidities,Recurrence,Primary Multiple Metastases,Metachronous Bilateral RCC,Last Visit,Date of Death,Cause of Death,Adjuvant Chemotherapy,Palliative Chemotherapy,Palliative Therapy
0,39,NaN,Ч,S,C-H,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,09.01.2010,cancer,NaN,NaN,NaN
1,57,NaN,Ч,D,C,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,13.12.2010,cancer,NaN,NaN,NaN
2,64,R,Ч,D,H,NaN,+,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11.02.2024,NaN,NaN,NaN,NaN,NaN
3,64,NaN,Ж,S,H,NaN,NaN,+,NaN,NaN,...,NaN,NaN,NaN,NaN,19.02.2024,NaN,NaN,NaN,NaN,NaN
4,59,NaN,Ч,S,B,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,22.11.2008,інше,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,60,RL,Ч,D,С/Н,NaN,+,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,01.05.2024,NaN,NaN,NaN,NaN,NaN
996,51,NaN,Ч,S,С/В,NaN,NaN,+,NaN,NaN,...,NaN,NaN,NaN,NaN,28.02.2024,NaN,NaN,NaN,NaN,NaN
997,65,R,Ж,S,В,2,NaN,NaN,NaN,NaN,...,NaN,12.06.2018,24.09.2018,+,NaN,27.09.2019,cancer,NaN,NaN,NaN
998,74,RL,Ч,S,С/Н,NaN,NaN,+,NaN,NaN,...,Cancer простати рТ3b сN0 М0 Gleason 8 ІІІ-ІІІ....,NaN,NaN,NaN,08.03.2024,NaN,NaN,NaN,NaN,NaN
999,78,L,Ж,D,С/В,NaN,NaN,+,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,02.01.2019,інше,NaN,NaN,NaN

In [10]:
# Видалення зайвих пробілів у назвах колонок
df.columns = df.columns.str.strip()
df

,Age,R,Sex,D/S,Location,pT,pT1a,pT1b,Invasion,V+,...,Comorbidities,Recurrence,Primary Multiple Metastases,Metachronous Bilateral RCC,Last Visit,Date of Death,Cause of Death,Adjuvant Chemotherapy,Palliative Chemotherapy,Palliative Therapy
0,39,NaN,Ч,S,C-H,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,09.01.2010,cancer,NaN,NaN,NaN
1,57,NaN,Ч,D,C,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,13.12.2010,cancer,NaN,NaN,NaN
2,64,R,Ч,D,H,NaN,+,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11.02.2024,NaN,NaN,NaN,NaN,NaN
3,64,NaN,Ж,S,H,NaN,NaN,+,NaN,NaN,...,NaN,NaN,NaN,NaN,19.02.2024,NaN,NaN,NaN,NaN,NaN
4,59,NaN,Ч,S,B,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,22.11.2008,інше,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,60,RL,Ч,D,С/Н,NaN,+,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,01.05.2024,NaN,NaN,NaN,NaN,NaN
996,51,NaN,Ч,S,С/В,NaN,NaN,+,NaN,NaN,...,NaN,NaN,NaN,NaN,28.02.2024,NaN,NaN,NaN,NaN,NaN
997,65,R,Ж,S,В,2,NaN,NaN,NaN,NaN,...,NaN,12.06.2018,24.09.2018,+,NaN,27.09.2019,cancer,NaN,NaN,NaN
998,74,RL,Ч,S,С/Н,NaN,NaN,+,NaN,NaN,...,Cancer простати рТ3b сN0 М0 Gleason 8 ІІІ-ІІІ....,NaN,NaN,NaN,08.03.2024,NaN,NaN,NaN,NaN,NaN
999,78,L,Ж,D,С/В,NaN,NaN,+,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,02.01.2019,інше,NaN,NaN,NaN

In [11]:
print(df.dtypes)

Age                                  object
R                                    object
Sex                                  object
D/S                                  object
Location                             object
pT                                   object
pT1a                                 object
pT1b                                 object
Invasion                             object
V+                                   object
Renal Vein Invasion                  object
Inferior Vena Cava Invasion          object
pT3a                                 object
pT3b                                 object
pT3c                                 object
Adrenal Gland Invasion               object
MRT N                                object
CT N                                 object
Ultrasound N                         object
pN                                   object
pN+                                  object
M                                    object
Lung Metastases                      object
Adrenal Gland                        object
Bone Metastases                      object
Liver Metastases                     object
No Regional Lymph Node Metastasis    object
Other                                object
G                                    object
Stage                                object
Surgery                              object
Adrenalectomy                        object
Clear Cell RCC                       object
Papillary RCC                        object
Chromophobe RCC                      object
Bellini                              object
Leiomyosarcoma                       object
Tumor Necrosis Foci                  object
Sarcomatoid Elements                 object
Microvascular Invasion               object
Comorbidities                        object
Recurrence                           object
Primary Multiple Metastases          object
Metachronous Bilateral RCC           object
Last Visit                           object
Date of Death                        object
Cause of Death                       object
Adjuvant Chemotherapy                object
Palliative Chemotherapy              object
Palliative Therapy                   object
dtype: object

In [72]:
df["Age"] = df["Age"].replace("?", np.nan)  # Замінюємо ? на NaN
print(df["Age"].isnull().sum())

1

In [73]:
median_age = int(df["Age"].median())  # Перетворюємо у ціле число
print(f"Медіана віку: {median_age}")

# Заповнюємо NaN медіаною
df["Age"].fillna(median_age, inplace=True)

Медіана віку: 59

In [74]:
df["Age"] = df["Age"].astype(int)

In [75]:
print(df["Age"].isnull().sum())

0

In [79]:
min_age = df["Age"].min()
max_age = df["Age"].max()

# Displaying the results
print(f"Minimum Age: {min_age}")
print(f"Maximum Age: {max_age}")

Minimum Age: 17
Maximum Age: 83

In [80]:
# Creating age groups
df["Age group"] = pd.cut(df["Age"], bins=[0, 30, 50, 70, 100], labels=["Young", "Middle-aged", "Elderly", "Old"])

# Displaying the table with two columns
print(df[["Age", "Age group"]])

     Age    Age group
0     39  Middle-aged
1     57      Elderly
2     64      Elderly
3     64      Elderly
4     59      Elderly
..   ...          ...
995   60      Elderly
996   51      Elderly
997   65      Elderly
998   74          Old
999   78          Old

[1000 rows x 2 columns]

In [81]:
print(df["Age group"].value_counts())

Age group
Elderly        640
Middle-aged    215
Old            133
Young           12
Name: count, dtype: int64

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [12]:
df["R"].value_counts()

R
R      243
RL     154
L      108
         1
Name: count, dtype: int64

In [13]:
print(df["R"].isnull().sum())  # Кількість відсутніх значень

494

In [14]:
# Очищаємо колонку від зайвих пробілів
df["R"] = df["R"].str.strip()

# Замінюємо порожні значення та NaN на 'L'
df["R"] = df["R"].replace(["", " "], "L").fillna("L")

# Переконаємося, що залишилися лише потрібні категорії
df = df[df["R"].isin(["R", "L", "RL"])]

In [15]:
df["R"] = df["R"].astype("category")

In [16]:
print(df["R"].unique())  # Переконатися, що залишились лише ['R', 'L', 'RL']
print(df["R"].value_counts())  # Подивитися, скільки значень тепер у кожній категорії
print(df["R"].dtypes)  # Переконатися, що колонка тепер категорійна

['L', 'R', 'RL']
Categories (3, object): ['L', 'R', 'RL']
R
L     603
R     243
RL    154
Name: count, dtype: int64
category

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [17]:
df["Sex"].value_counts()

Sex
Ч    578
Ж    422
Name: count, dtype: int64

In [19]:
# Перейменовуємо "Ч" → "M", "Ж" → "F"
df['Sex'] = df['Sex'].replace({"Ч": "M", "Ж": "F"})

# Перетворюємо колонку в категорійний тип
df['Sex'] = df['Sex'].astype('category')

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [20]:
df["D/S"].value_counts()

D/S
D     503
S     495
 S      1
DU      1
Name: count, dtype: int64

In [21]:
# Видаляємо пробіли з усіх значень
df["D/S"] = df["D/S"].str.strip()

df['D/S'] = df['D/S'].astype('category')

In [22]:
print(df["D/S"].unique())  
print(df["D/S"].value_counts())  
print(df["D/S"].dtypes)

['S', 'D', 'DU']
Categories (3, object): ['D', 'DU', 'S']
D/S
D     503
S     496
DU      1
Name: count, dtype: int64
category

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [23]:
df["Location"].value_counts()

Location
С                              153
C                              116
В                              115
Н                              111
B                               98
H                               89
С/Н                             38
С/В                             35
C-H                             29
С-В                             23
C/H                             22
C-B                             19
С-Н                             18
B-C                             15
B/C                             14
В-Н                             10
C/B                              9
M                                9
В-С                              7
m(2)                             5
М                                5
B-H                              5
В/С                              4
-                                3
Н-В                              2
C/Н                              2
Н-С                              2
С_В                              2
В_Н                              2
m(3)                             1
B|C                              1
АН                               1
Dm                               1
Сm                               1
C/                               1
C|B                              1
ВМ                               1
С/H                              1
С/B                              1
C мультифокальна в динаміці      1
В-H                              1
С-B                              1
???                              1
H-C                              1
Н/С                              1
Name: count, dtype: int64

In [24]:
df["Location"].unique()

array(['C-H', 'C', 'H', 'B', 'C/H', 'B-H', 'B-C', 'H-C', 'B/C', '???',
       'В/С', 'В', 'С', 'Н', 'В-Н', 'С/Н', 'C-B', 'С-B', 'В-С', 'В-H',
       'C/B', 'С-Н', 'C/', 'C мультифокальна в динаміці', '-', 'С-В',
       'С/B', 'С/H', nan, 'C/Н', 'M', 'С/В', 'С_В', 'ВМ', 'М', 'C|B',
       'B|C', 'm(2)', 'Dm', 'АН', 'Н-В', 'm(3)', 'В_Н', 'Н-С', 'Сm',
       'Н/С'], dtype=object)

In [25]:
VALID_CATEGORIES = ["C", "H", "B", "M", "C-H", "C-B", "B-H", "B-C", "H-C"]

In [26]:
mapping = {
    # Основні категорії (виправлення російських літер та неправильних назв)
    "C": "C", "Сm": "C", "C мультифокальна в динаміці": "C", "C/": "C", "С": "C",
    "H": "H", "АН": "H", "H/": "H", "Н": "H", 
    "B": "B", "В": "B", "B/": "B",
    "M": "M", "М": "M",
    
    # Комбіновані локалізації (без об'єднання дзеркальних значень)
    "C-H": "C-H", "C/H": "C-H", "C-Н": "C-H", "С-H": "C-H", "С-Н": "C-H", "С/Н": "C-H", "C/Н": "C-H", "С/H": "C-H",
    "H-C": "H-C", "H/C": "H-C", "Н-С": "H-C", "Н/С": "H-C",  

    "C-B": "C-B", "C/B": "C-B", "С-B": "C-B", "С-Б": "C-B", "C_B": "C-B", "С/В": "C-B", "С_В": "C-B", "С/B": "C-B",
    "B-C": "B-C", "B|C": "B-C", "B/C": "B-C", "B/C": "B-C", "В-С": "B-C", "В/С": "B-C",

    "B-H": "B-H", "B/H": "B-H", "В-H": "B-H", "В-Н": "B-H", "В_Н": "B-H",
    "H-B": "H-B", "H-B": "H-B",  
    
    # Виправлення дублюючих помилок (без об'єднання)
    "B/C": "B-C", "C|B": "C-B", "C|H": "C-H", 
    "H/C": "H-C", "C_B": "C-B", "H-B": "H-B", "C-B": "C-B",

    # Некоректні або зайві значення
    "???": None, "-": None, "C/": "C", "H/": "H", "B/": "B", "C-": "C",
    "Dm": None, "m(2)": "M", "m(3)": "M", "ВМ": "B"
}


# Очистка пробілів та заміна за мапінгом
df["Location"] = df["Location"].str.strip().replace(mapping)

# Видаляємо всі значення, які не входять до VALID_CATEGORIES
# df = df[df["Location"].isin(VALID_CATEGORIES)]

In [27]:
print(df["Location"].unique())  # Перевіряємо унікальні значення
print(df["Location"].value_counts())  # Дивимося статистику
print(df["Location"].dtypes)  # Переконуємося, що колонка стала категорійною

['C-H' 'C' 'H' 'B' 'B-H' 'B-C' 'H-C' None 'C-B' 'С-В' nan 'M' 'Н-В']
Location
C      272
B      214
H      201
C-H    110
C-B     68
B-C     41
С-В     23
M       20
B-H     18
H-C      4
Н-В      2
Name: count, dtype: int64
object

In [28]:
nan_count = df["Location"].isna().sum()
print(f"Кількість NaN у колонці 'Location': {nan_count}")

Кількість NaN у колонці 'Location': 27

In [29]:
most_common = df["Location"].mode()[0]  # Найпоширеніше значення
df["Location"].fillna(most_common, inplace=True)
most_common

'C'

In [30]:
df["Location"] = df["Location"].astype("category")

In [31]:
print(df["Location"].unique())  # Перевіряємо унікальні значення
print(df["Location"].value_counts())

['C-H', 'C', 'H', 'B', 'B-H', ..., 'H-C', 'C-B', 'С-В', 'M', 'Н-В']
Length: 11
Categories (11, object): ['B', 'B-C', 'B-H', 'C', ..., 'H-C', 'M', 'Н-В', 'С-В']
Location
C      299
B      214
H      201
C-H    110
C-B     68
B-C     41
С-В     23
M       20
B-H     18
H-C      4
Н-В      2
Name: count, dtype: int64

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [32]:
df["pT"].value_counts()

pT
2                  246
1                  102
3                   32
4                   23
інвазія в миску     10
m(2)                 3
інвазія в вену       1
Name: count, dtype: int64

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [33]:
df["pT1a"].value_counts()

pT1a
+    205
Name: count, dtype: int64

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [34]:
df["pT1b"].value_counts()

pT1b
+    267
Name: count, dtype: int64

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [35]:
df["Invasion"].value_counts()

Invasion
+                             33
інвазія в фіброзну капсулу     2
інвазія в миску                1
інванзія в миску               1
інфільтрація                   1
Name: count, dtype: int64

In [36]:
df["V+"].value_counts()

V+
1                          103
метахр                       1
імплант в нирковій вені      1
+                            1
Name: count, dtype: int64

In [39]:
df["Renal Vein Invasion"].value_counts()

Renal Vein Invasion
+                               58
інвазія                          3
2                                2
онний                            1
інвазія ЛВ в вену                1
susp.mts                         1
імпланти з інвазією  стінку.     1
Name: count, dtype: int64

In [41]:
df["Inferior Vena Cava Invasion"].value_counts()

Inferior Vena Cava Invasion
+       43
НКР?     1
РпГЗ     1
Name: count, dtype: int64

In [42]:
df["pT3a"].value_counts()

pT3a
+    79
?     1
Name: count, dtype: int64

In [43]:
df["pT3b"].value_counts()

pT3b
+    42
Name: count, dtype: int64

In [44]:
df["pT3c"].value_counts()

pT3c
+    2
Name: count, dtype: int64

In [67]:
def classify_tnm(row):
    pT = str(row["pT"]).strip()
    pT1a = row["pT1a"]
    pT1b = row["pT1b"]
    invasion = str(row["Invasion"]).strip()
    v_plus = str(row["V+"]).strip()
    pT3a = str(row["pT3a"]).strip()
    pT3b = str(row["pT3b"]).strip()
    pT3c = str(row["pT3c"]).strip()

    # 1️⃣ Якщо є позначка у pT3a, pT3b або pT3c → використовуємо її без змін
    if pT3a == "+":
        return "pT3a"
    if pT3b == "+":
        return "pT3b"
    if pT3c == "+":
        return "pT3c"

    # 2️⃣ Якщо pT = 1 і більше нічого не вказано → pT1
    if pT == "1" and pT1a != "+" and pT1b != "+" and invasion == "nan" and v_plus == "nan":
        return "pT1"
    
    # 4️⃣ Якщо є інвазія в миску + васкулярна інвазія → pT3
    if "інвазія в миску" in invasion.lower() and v_plus in ["1", "+"]:
        return "pT3"
    
    if "інвазія в миску" in pT.lower():
        return "pT3"
    
    if "інвазія в вену" in pT.lower():
        return "pT3b"

    # 6️⃣ Якщо є інфільтрація → pT3
    if "інфільтрація" in invasion.lower():
        return "pT3"

    # 7️⃣ Якщо є васкулярна інвазія (V+) → pT3
    if v_plus in ["1", "+"]:
        return "pT3"

    # 8️⃣ Якщо pT3 + васкулярна інвазія → pT3
    if pT == "3" and v_plus in ["1", "+"]:
        return "pT3"

    # 9️⃣ Якщо pT4 → pT4
    if pT == "4":
        return "pT4"
    
    
    # 🔟 Класифікація за розміром пухлини
    if pT1a == "+":
        return "pT1a"
    elif pT1b == "+":
        return "pT1b"
    elif pT == "2":
        return "pT2"
    elif pT == "3":
        return "pT3"
    
    # 3️⃣ Якщо є **тільки інвазія в миску** без інших факторів → pT3
    if "інвазія в миску" in invasion.lower() and v_plus == "nan":
        return "pT3"
    
    if "m(2)" in pT.lower():
        return "pT3"
    
    if invasion == "+" and pT1a != "+" and pT1b != "+" and v_plus == "nan":
        return "pT3a"
    
    # 3️⃣ Якщо є тільки інвазія в фіброзну капсулу → pT3a
    if invasion == "інвазія в фіброзну капсулу" and pT1a != "+" and pT1b != "+" and v_plus in ["nan", "", "none"]:
        return "pT3a"

    
    # 11️⃣ Якщо немає специфічної класифікації, повертаємо "Unknown"
    return "Unknown"

# Додаємо нову колонку TNM
df["TNM"] = df.apply(classify_tnm, axis=1)

# Перетворюємо колонку в категорійну змінну
df["TNM"] = df["TNM"].astype("category")

In [68]:
# Вибираємо ключові колонки для збереження
selected_columns = ["pT", "pT1a", "pT1b", "Invasion", "V+", "TNM", "pT3a", "pT3b", "pT3c"]
df_selected = df[selected_columns]

# Зберігаємо у новий Excel-файл
df_selected.to_excel("TNM_classified_data.xlsx", index=False, engine="openpyxl")

print("Файл 'TNM_classified_data.xlsx' успішно збережено!")

Файл 'TNM_classified_data.xlsx' успішно збережено!

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [69]:
df["TNM"].value_counts()

TNM
pT1b    267
pT2     246
pT1a    205
pT1     102
pT3a     81
pT3b     43
pT3      38
pT4      16
pT3c      2
Name: count, dtype: int64

In [70]:
def general_tnm_classification(tnm):
    if tnm in ["pT1a", "pT1b", "pT1"]:  # Категорія 1
        return "1"
    elif tnm in ["pT2"]:  # Категорія 2
        return "2"
    elif tnm in ["pT3a", "pT3b", "pT3c", "pT3"]:  # Категорія 3
        return "3"
    elif tnm in ["pT4"]:  # Категорія 4
        return "4"
    else:
        return "Unknown"  # На випадок, якщо є значення поза списком

# Додаємо нову колонку "General_TNM"
df["General TNM"] = df["TNM"].apply(general_tnm_classification)

# Перетворюємо колонку в категорійну змінну
df["General TNM"] = df["General TNM"].astype("category")

# Перевіряємо результати
print(df["General TNM"].value_counts())

General TNM
1    574
2    246
3    164
4     16
Name: count, dtype: int64

<b>------------------------------------------------------------------------------------------------------------------------------------------------</b>

In [82]:
df["MRT N"].value_counts()

MRT N
0    25
-     5
1     3
Name: count, dtype: int64

In [83]:
df["CT N"].value_counts()

CT N
0    206
1     65
-     13
!      1
?      1
Name: count, dtype: int64

In [84]:
df["Ultrasound N"].value_counts()

Ultrasound N
0     163
-     114
1      27
?1      1
!       1
Name: count, dtype: int64

In [85]:
df["pN"].value_counts()

pN
-            51
1            27
10           23
3            22
5            21
2            17
8            17
9            15
15           14
4            13
6            13
7            12
14           11
13           11
12           11
11            9
16            8
17            7
21            7
19            7
18            5
24            4
29            4
22            4
20            4
k             3
42            2
27            2
31            2
28            2
25            2
23            2
48            1
2k(~5)+13     1
40            1
26            1
14+1          1
k+7           1
33            1
9+1/k         1
Name: count, dtype: int64

In [86]:
df["pN+"].value_counts()

pN+
0       199
1        19
3        11
2         9
4         8
5         4
10        4
13        2
12        2
20        1
k         1
13+1      1
16        1
8         1
1/k       1
Name: count, dtype: int64

In [87]:
df["M"].value_counts()

M
1                 115
?                  11
0                   4
ретроспективно      2
?знято              1
ретросп.            1
Name: count, dtype: int64

In [88]:
df["Lung Metastases"].value_counts()

Lung Metastases
+                                                                                                                                                                             72
знято                                                                                                                                                                          4
?                                                                                                                                                                              4
#ІМ’Я?                                                                                                                                                                         2
susp.                                                                                                                                                                          2
1                                                                                                                                                                              2
підтверджено при динамічному спостереженні                                                                                                                                     1
знято.                                                                                                                                                                         1
(D)+                                                                                                                                                                           1
кальцинат 10 мм. як наслідок перенесеного туберкульозу                                                                                                                         1
гранульми                                                                                                                                                                      1
susp. КТ 24.06.17 - в базальних відділах лівої легені 2 вогнища з чітким контуром до 8 мм. і 3 мм. перегляд в ЛДОРЛДЦ 15.07.17. КТ 21.08.19 - вогнищеві утвори обох легень     1
(S)                                                                                                                                                                            1
0                                                                                                                                                                              1
Name: count, dtype: int64

In [89]:
df["Adrenal Gland"].value_counts()

Adrenal Gland
+                                           8
оба                                         3
#ІМ’Я?                                      3
sinister                                    2
ретроспективно                              1
б/о.                                        1
dexter                                      1
dex. +                                      1
sin. +                                      1
sin.  +                                     1
ретроспективно (S)                          1
знято susp. (S) на КТ 25.02.20 -аденома.    1
sin.                                        1
susp.sinist.                                1
гіперплазія обох                            1
Name: count, dtype: int64

In [90]:
df["Bone Metastases"].value_counts()

Bone Metastases
+                                                                14
?                                                                 2
сіднична кістка                                                   1
знято на Остео...                                                 1
ретроспективно                                                    1
ретроспективно(болі в кістках поч.відмічати ч/3 6-12 міс п/о)     1
L5                                                                1
IX ребро зліва-видалено і ручка грудини-ПТ???                     1
XІ ребро зліва                                                    1
Name: count, dtype: int64

In [91]:
df["Liver Metastases"].value_counts()

Liver Metastases
+             12
?              4
гемангіоми     1
Name: count, dtype: int64

In [92]:
df["No Regional Lymph Node Metastasis"].value_counts()

No Regional Lymph Node Metastasis
+                                      25
?                                       4
в корені правої легені ЛВ 10Х21 мм.     1
Name: count, dtype: int64

Boolean

In [18]:


# Замінюємо "+" → True, порожні значення → False
for col in columns_to_convert:
    if col in df.columns:
        df[col] = df[col].apply(lambda x: True if x == "+" else False)

# Перетворюємо колонки у категорійний тип
df[columns_to_convert] = df[columns_to_convert].astype("bool")

In [19]:
print(df.dtypes)

Age                                    object
R                                      object
Sex                                  category
D/S                                  category
Location                               object
pT                                     object
pT1a                                     bool
pT1b                                     bool
Invasion in Paranephric Fat              bool
V+                                     object
Renal Vein Invasion                      bool
Inferior Vena Cava Invasion              bool
pT3a                                     bool
pT3b                                     bool
pT3c                                     bool
Adrenal Gland Invasion                 object
MRT N                                  object
CT N                                   object
Ultrasound N                           object
pN                                     object
pN+                                    object
M                                      object
Lung Metastases                          bool
Adrenal Gland                            bool
Bone Metastases                          bool
Liver Metastases                         bool
No Regional Lymph Node Metastasis        bool
Other                                  object
G                                      object
Stage                                  object
Surgery                                object
Adrenalectomy                          object
Clear Cell RCC                         object
Papillary RCC                          object
Chromophobe RCC                        object
Bellini                                object
Leiomyosarcoma                         object
Tumor Necrosis Foci                    object
Sarcomatoid Elements                   object
Microvascular Invasion                 object
Comorbidities                          object
Recurrence                             object
Primary Multiple Metastases            object
Metachronous Bilateral RCC             object
Last Visit                             object
Date of Death                          object
Cause of Death                         object
Adjuvant Chemotherapy                  object
Palliative Chemotherapy                object
Palliative Therapy                     object
dtype: object

In [20]:
df.head(10).style.set_properties(**{'text-align': 'left'}).set_table_styles([
    {'selector': 'th', 'props': [('text-align', 'left')]}])

In [ ]:
# Об'єднання схожих категорій
df['Metastases'] = df[['Lung Metastases', 'Bone Metastases', 'Liver Metastases', 'No Regional Lymph Node Metastasis']].sum(axis=1)
df.drop(columns=['Lung Metastases', 'Bone Metastases', 'Liver Metastases', 'No Regional Lymph Node Metastasis'], inplace=True)

df['Cancer Type'] = df[['Clear Cell RCC', 'Papillary RCC', 'Chromophobe RCC', 'Bellini', 'Leiomyosarcoma']].idxmax(axis=1)
df.drop(columns=['Clear Cell RCC', 'Papillary RCC', 'Chromophobe RCC', 'Bellini', 'Leiomyosarcoma'], inplace=True)

df['Therapy Type'] = df[['Adjuvant Chemotherapy', 'Palliative Chemotherapy', 'Palliative Therapy']].idxmax(axis=1)
df.drop(columns=['Adjuvant Chemotherapy', 'Palliative Chemotherapy', 'Palliative Therapy'], inplace=True)

df

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
# Закодування категорійних змінних
categorical_cols = df.select_dtypes(include=['object']).columns
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le
    
    
df

In [ ]:
# Масштабування числових колонок
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df

In [ ]:
# Збереження обробленого датасету
df.to_csv("/mnt/data/processed_data.csv", index=False)

print("Dataset preprocessing complete. Processed file saved as 'processed_data.csv'")

In [ ]:
# Визначення таргет-колонки
target_column = "рецидив"

# Обробка дат
for date_col in ["ост. візит", "дата смерті"]:
    if date_col in df.columns:
        df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

# Створення нових ознак на основі дат
if "ост. візит" in df.columns and "дата смерті" in df.columns:
    df["живий"] = df["дата смерті"].isna().astype(int)  # 1 - живий, 0 - помер
    df["тривалість спостереження"] = (df["ост. візит"] - df["ост. візит"].min()).dt.days
    df.drop(columns=["дата смерті", "ост. візит"], inplace=True)  # Видаляємо оригінальні дати

# Створення нової категорійної змінної "тип_пухлини"
relevant_columns = ["Lok", "Stage", "G", "світлоклітинний НКР", "папілярний НКР", "хромофобний НКР", "Bellini", "лейоміосаркома"]
df["тип_пухлини"] = df[relevant_columns].astype(str).agg('_'.join, axis=1)

# Видалення оригінальних колонок після об'єднання
df.drop(columns=relevant_columns, inplace=True)

# Обробка пропущених значень
df.fillna("Unknown", inplace=True)  # Заповнення пропущених значень

# Кодування категорійних змінних
label_encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    if col != target_column:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        label_encoders[col] = le

# Розділення на тренувальний та тестовий набір
X = df.drop(columns=[target_column])
y = df[target_column].apply(lambda x: 1 if x == "Yes" else 0)  # Бінаризація таргета

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Масштабування числових змінних
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Навчання моделей
models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"Model: {name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print("-" * 50)

<div class="alert alert-danger alertdanger" style="margin-top: 20px">
<b style="font-size: 2em; font-weight: bold;"> Question #1: </b>
    
<b>Check the bottom 10 rows of data frame "df".</b>
</div>

In [ ]:
# Write your code below and press Shift+Enter to execute

<details><summary>Click here for the solution</summary>

```python
print("The last 10 rows of the dataframe\n")
df.tail(10)
```

 <div class="alert alert-danger alertdanger" style="margin-top: 20px">
<b style="font-size: 2em; font-weight: bold;"> Question #2: </b>
    
<b>Find the name of the columns of the dataframe.</b> <br>
<b>Hint: use <code>.columns</code> method</b>
</div>

In [ ]:
# Write your code below and press Shift+Enter to execute

<details><summary>Click here for the solution</summary>

```python
print(df.columns)
```

</details>

<h3>Update Headers</h3>
<p>
We will create a list "headers" that include correct column names in order.
Then, we use <code>dataframe.columns = headers</code> to replace the headers with the list we created.
</p>

In [ ]:
# create new headers list
headers = ['Invoice Number', 'Stock Code', 'Description', 'Quantity', 'Invoice Date','Unit Price', 'Customer ID', 'Country']
print("headers\n", headers)


We replace headers and recheck our dataframe:

In [ ]:
df.columns = headers
df.head(5)

Now, we have successfully added the correct headers into the dataframe.

<h1><a name="basic_insight" style="color: black; text-decoration: none;">Basic Insight of Dataset</a></h1>
<p>
After reading data into Pandas dataframe, it is time for us to explore the dataset.<br>

There are several ways to obtain essential insights of the data to help us better understand our dataset.

</p>

<h2>Data Types</h2>
<p>
Data has a variety of types.<br>

The main types stored in Pandas dataframes are <b>object</b>, <b>float</b>, <b>int</b>, <b>bool</b> and <b>datetime64</b>. In order to better learn about each attribute, it is always good for us to know the data type of each column. In Pandas:

</p>

dataframe.dtypes


<p>
A series with the data type of each column is returned.
</p>

In [ ]:
# check the data type of data frame "df" by .dtypes
df.dtypes

<p>
As shown above, it is clear to see that the data type of "Quantity" is <code>int64</code>, "Invoice Number", "Stock Code", "Description", "Invoice Date", "Country" are <code>object</code>, and "Unit Price", "Customer ID " are <code>float64</code>.
</p>
<p>
These data types can be changed; we will learn how to accomplish this in a later module.
</p>

<h2>Describe</h2>
If we would like to get a statistical summary of each column e.g. count, column mean value, column standard deviation, etc., we use the describe method:

dataframe.describe()

In [ ]:
df.describe()

<p>
This shows the statistical summary of all numeric-typed (int, float) columns.<br>

For example, the attribute "Quantity" has 542014 counts, the mean value of this column is 9.555285, the standard deviation is 218.060485, the minimum value is -80995, 25th percentile is 1, 50th percentile is 3, 75th percentile is 10, and the maximum value is 80995. <br>

</p>

<div class="alert alert-danger alertdanger" style="margin-top: 20px">
<b style="font-size: 2em; font-weight: bold;"> Question #3: </b>

<p>
You can select the columns of a dataframe by indicating the name of each column. For example, you can select the three columns as follows:
</p>
<p>
    <code>dataframe[[' column 1 ',column 2', 'column 3']]</code>
</p>
<p>
Where "column" is the name of the column, you can apply the method  ".describe()" to get the statistics of those columns as follows:
</p>
<p>
    <code>dataframe[[' column 1 ',column 2', 'column 3'] ].describe()</code>
</p>

Apply the  method to ".describe()" to the columns 'Unit Price' and 'Quantity'.

</div>

In [ ]:
# Write your code below and press Shift+Enter to execute

<details><summary>Click here for the solution</summary>

```python
df[['Unit Price', 'Quantity']].describe()
```

</details>

<p>
Below you get the maximum value in column "Unit Price".
</p>

In [ ]:
df["Unit Price"].describe()["max"]

<h2>Info</h2>
Another method you can use to check your dataset is:

<code>dataframe.info()</code>

It provides a concise summary of your DataFrame.

This method prints information about a DataFrame including the index dtype and columns, non-null values and memory usage.

In [ ]:
# look at the info of "df"
df.info()

<h2>Save Dataset</h2>
<p>
Correspondingly, Pandas enables us to save the dataset to csv. By using the <code>dataframe.to_csv()</code> method, you can add the file path and name along with quotation marks in the brackets.
</p>
<p>
For example, if you would save the dataframe <b>df</b> as <b>automobile.csv</b> to your local machine, you may use the syntax below, where <code>index = False</code> means the row names will not be written.
</p>

df.to_csv("retail-updated-dataset.csv", index=False)

In [ ]:
df.to_csv("retail-dataset-lab2.csv", index=False)

We can also read and save other file formats. We can use similar functions like **`pd.read_csv()`** and **`df.to_csv()`** for other data formats. The functions are listed in the following table:

<h2>Read/Save Other Data Formats</h2>

| Data Formate |        Read       |            Save |
| ------------ | :---------------: | --------------: |
| csv          |  `pd.read_csv()`  |   `df.to_csv()` |
| json         |  `pd.read_json()` |  `df.to_json()` |
| excel        | `pd.read_excel()` | `df.to_excel()` |
| hdf          |  `pd.read_hdf()`  |   `df.to_hdf()` |
| sql          |  `pd.read_sql()`  |   `df.to_sql()` |
| ...          |        ...        |             ... |

<h1>Excellent! You have just completed Lab. 1!</h1>

### Thank you for completing this lab!

## Author

<a href="https://author.skills.network/instructors/veronika_lanchuv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkGuidedProjectsIBMSkillsNetworkGPXX08J0EN2930-2023-01-01">Veronika Lanchuv</a>

### Other Contributors

<a href="https://author.skills.network/instructors/yaroslav_vyklyuk_2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkGuidedProjectsIBMSkillsNetworkGPXX08J0EN2930-2023-01-01">Yaroslav Vyklyuk</a>

<a href="https://author.skills.network/instructors/olga_kavun?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkGuidedProjectsIBMSkillsNetworkGPXX08J0EN2930-2023-01-01">Olga Kavun</a>


## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                 |
| ----------------- | ------- | ---------- | ---------------------------------- |
| 2022-03-25        | 2.0     | Veronika   | lab is done                        |

<hr>

## <h3 align="center"> © IBM Corporation 2023. All rights reserved. <h3/>